version: '3.8'

services:
  postgres:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: payDemo
      POSTGRES_USER: gopay_admin
      POSTGRES_PASSWORD: gP@y2024S3cur3!
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gopay_admin -d payDemo"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: